/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gzxn3o1sZf6
 */
import Link from "next/link";
import {
  NavigationMenuLink,
  NavigationMenuItem,
  NavigationMenuList,
  NavigationMenu,
} from "@/components/ui/navigation-menu";
import { Button } from "@/components/ui/button";
import Hero from "./Hero";
import Overview from "./sections/Overview";
import Faq from "./sections/faq";
import Schedule from "./sections/Schedule";
import Competitions from "./sections/Competitions";
import Speakers from "./sections/Speakers";
import Sponsors from "./sections/Sponsors";

export function HomePage() {
  return (
    <div className="flex flex-col min-h-screen bg-[#f7f1fe] dark:bg-[#411972]">
      <header className="flex items-center justify-between px-4 py-2 border-b border-[#9e3ffd]">
        <Link className="flex items-center gap-2" href="#">
          <MountainIcon className="h-6 w-6 text-[#9e3ffd]" />
          <span className="text-lg font-semibold text-[#411972] dark:text-[#debdff]">
            Tech SumMIT 2024
          </span>
        </Link>
        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link
                  className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-[#f7f1fe] px-4 py-2 text-sm font-medium transition-colors hover:bg-[#debdff] hover:text-[#411972] focus:bg-[#debdff] focus:text-[#411972] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#debdff]/50 data-[state=open]:bg-[#debdff]/50 dark:bg-[#411972] dark:hover:bg-[#9e3ffd] dark:hover:text-[#f7f1fe] dark:focus:bg-[#9e3ffd] dark:focus:text-[#f7f1fe] dark:data-[active]:bg-[#9e3ffd]/50 dark:data-[state=open]:bg-[#9e3ffd]/50"
                  href="#"
                >
                  Home
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link
                  className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-[#f7f1fe] px-4 py-2 text-sm font-medium transition-colors hover:bg-[#debdff] hover:text-[#411972] focus:bg-[#debdff] focus:text-[#411972] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#debdff]/50 data-[state=open]:bg-[#debdff]/50 dark:bg-[#411972] dark:hover:bg-[#9e3ffd] dark:hover:text-[#f7f1fe] dark:focus:bg-[#9e3ffd] dark:focus:text-[#f7f1fe] dark:data-[active]:bg-[#9e3ffd]/50 dark:data-[state=open]:bg-[#9e3ffd]/50"
                  href="#"
                >
                  Schedule
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link
                  className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-[#f7f1fe] px-4 py-2 text-sm font-medium transition-colors hover:bg-[#debdff] hover:text-[#411972] focus:bg-[#debdff] focus:text-[#411972] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#debdff]/50 data-[state=open]:bg-[#debdff]/50 dark:bg-[#411972] dark:hover:bg-[#9e3ffd] dark:hover:text-[#f7f1fe] dark:focus:bg-[#9e3ffd] dark:focus:text-[#f7f1fe] dark:data-[active]:bg-[#9e3ffd]/50 dark:data-[state=open]:bg-[#9e3ffd]/50"
                  href="#"
                >
                  Competitions
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link
                  className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-[#f7f1fe] px-4 py-2 text-sm font-medium transition-colors hover:bg-[#debdff] hover:text-[#411972] focus:bg-[#debdff] focus:text-[#411972] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#debdff]/50 data-[state=open]:bg-[#debdff]/50 dark:bg-[#411972] dark:hover:bg-[#9e3ffd] dark:hover:text-[#f7f1fe] dark:focus:bg-[#9e3ffd] dark:focus:text-[#f7f1fe] dark:data-[active]:bg-[#9e3ffd]/50 dark:data-[state=open]:bg-[#9e3ffd]/50"
                  href="#"
                >
                  Speakers
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link
                  className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-[#f7f1fe] px-4 py-2 text-sm font-medium transition-colors hover:bg-[#debdff] hover:text-[#411972] focus:bg-[#debdff] focus:text-[#411972] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#debdff]/50 data-[state=open]:bg-[#debdff]/50 dark:bg-[#411972] dark:hover:bg-[#9e3ffd] dark:hover:text-[#f7f1fe] dark:focus:bg-[#9e3ffd] dark:focus:text-[#f7f1fe] dark:data-[active]:bg-[#9e3ffd]/50 dark:data-[state=open]:bg-[#9e3ffd]/50"
                  href="#"
                >
                  Sponsors
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link
                  className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-[#f7f1fe] px-4 py-2 text-sm font-medium transition-colors hover:bg-[#debdff] hover:text-[#411972] focus:bg-[#debdff] focus:text-[#411972] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#debdff]/50 data-[state=open]:bg-[#debdff]/50 dark:bg-[#411972] dark:hover:bg-[#9e3ffd] dark:hover:text-[#f7f1fe] dark:focus:bg-[#9e3ffd] dark:focus:text-[#f7f1fe] dark:data-[active]:bg-[#9e3ffd]/50 dark:data-[state=open]:bg-[#9e3ffd]/50"
                  href="#"
                >
                  FAQ
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link
                  className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-[#f7f1fe] px-4 py-2 text-sm font-medium transition-colors hover:bg-[#debdff] hover:text-[#411972] focus:bg-[#debdff] focus:text-[#411972] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#debdff]/50 data-[state=open]:bg-[#debdff]/50 dark:bg-[#411972] dark:hover:bg-[#9e3ffd] dark:hover:text-[#f7f1fe] dark:focus:bg-[#9e3ffd] dark:focus:text-[#f7f1fe] dark:data-[active]:bg-[#9e3ffd]/50 dark:data-[state=open]:bg-[#9e3ffd]/50"
                  href="#"
                >
                  Register
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>
        <Button
          className="border-[#9e3ffd] text-[#9e3ffd] hover:bg-[#9e3ffd] hover:text-[#f7f1fe] dark:border-[#debdff] dark:text-[#debdff] dark:hover:bg-[#debdff] dark:hover:text-[#411972]"
          variant="outline"
        >
          Register
        </Button>
      </header>
      <main className="flex-1">
        <Hero />
        <Overview />
        <Schedule />
        <Competitions />
        <Speakers />
        <Sponsors />
        <Faq />
      </main>
    </div>
  );
}

function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
